; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
	blynkkk/Blynk@^1.3.2
	paulstoffregen/OneWire@^2.3.8
	adafruit/DHT sensor library@^1.4.6
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
	madhephaestus/ESP32Servo@^3.0.5
build_flags =
	-I../../dev-projects/01_color_sensor/src
	-I../../dev-projects/02_servo_sorter/src
	-I../../dev-projects/03_conveyor_motor/src
	-I../../dev-projects/04_emergency_stop/src
	-I../../dev-projects/05_ui_display/src
	-I../../dev-projects/06.1_iot_mqtt/src
	-I../../dev-projects/07_ir_trigger_and_counter/src
build_src_filter =
	+<../..//dev-projects/01_color_sensor/src/ColorSensor.cpp>
	+<../..//dev-projects/02_servo_sorter/src/ServoSorter.cpp>
	+<../..//dev-projects/03_conveyor_motor/src/ConveyorMotor.cpp>
	+<../..//dev-projects/04_emergency_stop/src/EmergencyStop.cpp>
	+<../..//dev-projects/05_ui_display/src/UI.cpp>
	+<../..//dev-projects/06.1_iot_mqtt/src/IoTBlynk.cpp>
	+<../..//dev-projects/07_ir_trigger_and_counter/src/IRTrigger.cpp>
	+<src/main.cpp>
